src/java/edu/udesc/guilherme/pellizzetti/jsf_jpa/controlador/AlunoController.java
package edu.udesc.guilherme.pellizzetti.jsf_jpa.controlador;

import edu.udesc.guilherme.pellizzetti.jsf_jpa.entidade.Aluno;
import edu.udesc.guilherme.pellizzetti.jsf_jpa.util.JsfUtil;
import edu.udesc.guilherme.pellizzetti.jsf_jpa.util.PaginationHelper;
import edu.udesc.guilherme.pellizzetti.jsf_jpa.facade.AlunoFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("alunoController")
@SessionScoped
public class AlunoController implements Serializable {

    private Aluno current;
    private DataModel items = null;
    @EJB
    private edu.udesc.guilherme.pellizzetti.jsf_jpa.facade.AlunoFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public AlunoController() {
    }

    public Aluno getSelected() {
        if (current == null) {
            current = new Aluno();
            selectedItemIndex = -1;
        }
        return current;
    }

    private AlunoFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "Listar";
    }

    public String prepareView() {
        current = (Aluno) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Listar";
    }

    public String prepareCreate() {
        current = new Aluno();
        selectedItemIndex = -1;
        return "Criar";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AlunoCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Aluno) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Editar";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AlunoUpdated"));
            return "Listar";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Aluno) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "Listar";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "Listar";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "Listar";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AlunoDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "Listar";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "Listar";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Aluno getAluno(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Aluno.class)
    public static class AlunoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AlunoController controller = (AlunoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "alunoController");
            return controller.getAluno(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Aluno) {
                Aluno o = (Aluno) object;
                return getStringKey(o.getIdAluno());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Aluno.class.getName());
            }
        }

    }

}

web/aluno/Criar.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateAlunoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateAlunoLabel_nomeAluno}" for="nomeAluno" />
                    <h:inputText id="nomeAluno" value="#{alunoController.selected.nomeAluno}" title="#{bundle.CreateAlunoTitle_nomeAluno}" required="true" requiredMessage="#{bundle.CreateAlunoRequiredMessage_nomeAluno}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{alunoController.create}" value="#{bundle.CreateAlunoSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{alunoController.prepareList}" value="#{bundle.CreateAlunoShowAllLink}" immediate="true"/>
                <br />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/aluno/Editar.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditAlunoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditAlunoLabel_idAluno}" for="idAluno" />
                    <h:inputText id="idAluno" value="#{alunoController.selected.idAluno}" title="#{bundle.EditAlunoTitle_idAluno}" required="true" requiredMessage="#{bundle.EditAlunoRequiredMessage_idAluno}"/>
                    <h:outputLabel value="#{bundle.EditAlunoLabel_nomeAluno}" for="nomeAluno" />
                    <h:inputText id="nomeAluno" value="#{alunoController.selected.nomeAluno}" title="#{bundle.EditAlunoTitle_nomeAluno}" required="true" requiredMessage="#{bundle.EditAlunoRequiredMessage_nomeAluno}"/>
                </h:panelGrid>
                <h:commandLink action="#{alunoController.update}" value="#{bundle.EditAlunoSaveLink}"/>
                <br />
                <br />
                <br />
                <h:commandLink action="#{alunoController.prepareList}" value="#{bundle.EditAlunoShowAllLink}" immediate="true"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/aluno/Listar.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListAlunoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <br />
                <h:outputText escape="false" value="#{bundle.ListAlunoEmpty}" rendered="#{alunoController.items.rowCount == 0}"/>
                <br />
                <h:panelGroup rendered="#{alunoController.items.rowCount > 0}">
                    <h:outputText value="#{alunoController.pagination.pageLastItem + 1}/#{alunoController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{alunoController.previous}" value="#{bundle.Previous}" rendered="#{alunoController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{alunoController.next}" value="#{bundle.Next}" rendered="#{alunoController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{alunoController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="width:35%;border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAlunoTitle_idAluno}"/>
                            </f:facet>
                            <h:outputText value="#{item.idAluno}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAlunoTitle_nomeAluno}"/>
                            </f:facet>
                            <h:outputText value="#{item.nomeAluno}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Ações"/>
                            </f:facet>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{alunoController.prepareEdit}" value="#{bundle.ListAlunoEditLink}"/>&nbsp;&nbsp;
                            <h:outputText value=" "/>
                            <h:commandLink action="#{alunoController.destroy}" value="#{bundle.ListAlunoDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{alunoController.prepareCreate}" value="#{bundle.ListAlunoCreateLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Titulo Padrão</ui:insert></title>
        <h:outputStylesheet library="css" name="main.css"/>
    </h:head>

    <h:body>
        <h1>
            <ui:insert name="title">Titulo Padrão</ui:insert>
        </h1>
        <p>
            <ui:insert name="body">Body Padrão</ui:insert>
        </p>
    </h:body>

</html>